### ISSUE TITLE
Apple Icon Dropdown should overlap Windows.

### ISSUE THREAD

**Issue by mirkoRainer** [Renovamen/playground-macos#3]
![image](https://user-images.githubusercontent.com/52899592/117538694-5bebb180-afd5-11eb-8789-55fb89391d72.png)
Photo from screenshot using Edge browser in iOS on iPhone XS Max. 

In true MacOS, the Apple icon dropdown in the top left would overlay windows. This is not the case in your site. 

Either way, awesome site! Good job!

**Comment by Renovamen** [comment]
Hmmm it seems harder than I thought. Before making the dropdown menu always overlay windows, I have to limit the movement boundary of windows below topbar, or the ui will seem strange. However, I use [react-rnd]() for dragging and resizing windows and it's not easy to set boundaries in react-rnd...

I'll try to find out a solution but this issue may not be solved immediately. (Also, pull requests are welcome

**Comment by mirkoRainer** [comment]
I recommend looking for something to overlay the dropdown so that it is always rendered on top of things at a fixed positive.
https://www.npmjs.com/package/react-overlays comes to mind but might not be the right solution.

Is this what you tried?

**Comment by AXiLiYa** [comment]
I try to set z-index of the dropdown menu and the top toolbar (the div of dropdown menu), it seems to work well. In my opinion, the z-index of top toolbar and the dropdown menu should be the max of the page so that it can always show over other element.
![image](https://user-images.githubusercontent.com/58588033/118094435-4d503080-b401-11eb-9f84-371bc728d7f6.png)

**Comment by Renovamen** [comment]
> I try to set z-index of the dropdown menu and the top toolbar (the div of dropdown menu), it seems to work well. In my opinion, the z-index of top toolbar and the dropdown menu should be the max of the page so that it can always show over other element.
> ![image](https://user-images.githubusercontent.com/58588033/118094435-4d503080-b401-11eb-9f84-371bc728d7f6.png)

That's right. However, in that way, when dragging the window to the top of the screen, it will be overlapped by the topbar, which seems weird:

![image](https://user-images.githubusercontent.com/29454156/118217874-ebe39c80-b4a8-11eb-9d7f-8f49549d8af9.png)

So I guess I should limit the movement boundary of windows below the topbar (red line), but it's seems not easy in react-rnd...

**Comment by AXiLiYa** [comment]
> > I try to set z-index of the dropdown menu and the top toolbar (the div of dropdown menu), it seems to work well. In my opinion, the z-index of top toolbar and the dropdown menu should be the max of the page so that it can always show over other element.
> > ![image](https://user-images.githubusercontent.com/58588033/118094435-4d503080-b401-11eb-9f84-371bc728d7f6.png)
> 
> That's right. However, in that way, when dragging the window to the top of the screen, it will be overlapped by the topbar, which seems weird:
> 
> ![image](https://user-images.githubusercontent.com/29454156/118217874-ebe39c80-b4a8-11eb-9d7f-8f49549d8af9.png)
> 
> So I guess I should limit the movement boundary of windows below the topbar (red line), but it's seems not easy in react-rnd...

I never use react before(always using vue), so it maybe hard to change the code directly and properly for me. I just read the doc of react-rnd and I understand the question is to ensure that the x and y of the window do not extend beyond the desktop area. And I find that the problem can be solved with putting the rnd in a div. I try to write a [example](https://codesandbox.io/s/rnd-test-0khc1?file=/src/App.js). Hope it can help you deal with this issue.

**Comment by Renovamen** [comment]
> I just read the doc of react-rnd and I understand the question is to ensure that the x and y of the window do not extend beyond the desktop area. And I find that the problem can be solved with putting the rnd in a div. I try to write a [example](https://codesandbox.io/s/rnd-test-0khc1?file=/src/App.js). Hope it can help you deal with this issue.

Yes, theoretically, movement boundaries can be set using div in react-rnd. But this would be difficult in practice in this case, because the size and position of the boundary div should adapts according to the window size. Here's a simple sketch:

![image](https://user-images.githubusercontent.com/29454156/118765639-effb2a00-b8ad-11eb-812d-88e04344ae59.png)

For window1 (blue), the boundary div should be the blue box. But for window2 (another window, or resized window1), the boundary div transforms to the red box.

So in my opinion, this way is neither easy nor elegant. I guess it would be much easier if react-rnd provides a way to set bounds prop with a position object, just like what [react-draggable](https://github.com/react-grid-layout/react-draggable) (one of react-rnd's dependencies) does. I'll try to submit a pr to react-rnd when I have time (although I hope some others could do it hahaha

**Comment by Renovamen** [comment]
@mirkoRainer @AXiLiYa Hi, finally I took @AXiLiYa's advice and added a boundary for rnds via putting them in a parent div. In fact it's much easier than I thought hahaha. Now this problem should be solved, have a look at the website. Thank you!

**Comment by mirkoRainer** [comment]
Nice!
